server:
  port: 8080
  tomcat:
    threads.max: 50
    max-connections: 100
    max-http-form-post-size: 35MB
    connection-timeout: 60000
    remoteip:
      remote-ip-header: x-forward-for
    uri-encoding: UTF-8
  max-http-header-size: 8096
  servlet:
    encoding:
      force: true
      charset: UTF-8
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  mail:
    host: smtp.qq.com
    username: 1303783484@qq.com
    password: ywdwyxbpabyhfidg
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  datasource:
    username: poetize
    password: root1234
    url: jdbc:mysql://47.93.39.67:3306/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

user:
  code:
    format: 【utopian.cn】%s为本次验证的验证码，请在5分钟内完成验证。为保证账号安全，请勿泄漏此验证码。
  subscribe:
    format: 【utopian.cn】您订阅的专栏【%s】新增一篇文章：%s。

store:
  type: qiniu

local:
  enable: true
  uploadUrl: $$$$服务器上传路径，仿照【/home/file/】
  downloadUrl: $$$$服务器访问路径，仿照【https://poetize.cn/static/】

qiniu:
  enable: true
  accessKey: VocfGZPT06JMWrKa80JU1CPDBTjLHbjmmOxw9VJ1
  secretKey: 52v-sh9mSgrUqxvyBgp--2Aow8AbDXpk9Aq3bF9w
  bucket: com-api
  downloadUrl: s623dfiwp.bkt.clouddn.com


logging:
  config: classpath:logback-spring.xml
  file:
    path: logging

